var hbdi_questions = ["I am intellectually curious and have a love for learning.",
"I am a rational thinker who tends to contain emotions.",
"I am realistic and prefer concrete interests.",
"I am flexible and like to go with the flow.",
"I enjoy engaging in complex thought.",
"I make my decisions primarily based on facts and logic.",
"I am generally an instinctive and action-oriented person.",
"I listen to emotions and intuition while making decisions.",
"I feel at home with abstract concepts and ideas.",
"I am more of a planner than someone who acts spontaneously.",
"I learn best with a practical, hands-on style.",
"I am more people-oriented than task-oriented.",
"I prefer a job with high intellectual stimulation.",
"I highly favor efficiency and accuracy in my lifestyle.",
"I am better at executing ideas than generating them.",
"I am enthusiastic and express my feelings easily."];

var bc_questions = ["I make decisions quickly and instinctively.",
"I try to look at the bright side as much as possible.",
"I prefer taking a more passive role in groups.",
"I have high standards and try to perfect things.",
"I like taking risks and beating the odds.",
"I prefer doing what I feel like to do instead of scheduling.",
"I am sensitive and try to avoid conflict as much as possible.",
"I am generally more task-oriented than people-oriented.",
"I like to be on the cutting edge when it comes to innovation.",
"I see the big picture and how everything is connected together.",
"I tend to be methodical and careful in my decisions.",
"I am generally logical and tend to contain my emotions.",
"I brush off mistakes and tolerate necessary conflict.",
"I freely express my emotions and interests with others.",
"I prefer using methods which has worked before.",
"I like to stay organized and focused.",
"I take charge and try to make things happen.",
"I heavily prefer cooperation over competition.",
"I am considered as introspective and reserved.",
"I tend to be skeptical of people until I know them better."];

var meta_questions = ["I highly value teamwork and delegate people to get things done.",
"I focus on the present and live in the moment.",
"I am keen on fighting and enjoy combat activities.",
"I am generally considered as gifted by others.",
"I actively give to others in order to maintain relationships.",
"I am generally a practical and hands-on person.",
"I am highly territorial and protective of my comfort.",
"I am pretty serious and don't laugh often.",
"I am generally a highly confident and decisive person.",
"I am generally emotionally stable and cheerful.",
"I would do anything to stand out as much as I can.",
"I can handle stress well thanks to my patience.",
"I can be unwilling to engage in deep thought.",
"I vastly prefer being with others than alone time.",
"I tend to show my authentic, real self to everyone.",
"I can easily focus on one thing for a long time.",
"I heavily favor my instincts in my decisions.",
"I am spontaneous and playful but also reckless.",
"I can be uncooperative and too willing to fight.",
"I support others by deeply understanding them.",
"I can be impatient and get angry easily.",
"I am generally humble and dislike standing out too much.",
"I tend to enjoy a great adventure and thrill.",
"I don't like memorization and I prefer fully understanding concepts."];

var os_questions = ["I often give good impressions to others.",
"I am emotionally stable and handle stress well.",
"I often find myself taking charge of organizations.",
"I vastly prefer function over good looks.",
"I often worry about how others perceive me.",
"I have a hard time accepting my own problems.",
"I am a highly strategic problem solver.",
"I enjoy variety and novelty in my life.",
"I am idealistic and believe that everything can be improved.",
"I often work on my skills to get better at them.",
"I can easily become overly controlling and bossy.",
"I am unstable and prone to mood swings.",
"I am generally enthusiastic and optimistic.",
"I am generally relaxed and creative.",
"I really enjoy high quality video games.",
"I hate being limited and prefer to do whatever I want.",
"I have a generally sleek and minimalistic style.",
"I can be overly relaxed and slow to start.",
"I am efficient and this makes me well-respected.",
"I have a hard time adapting to my social environment.",
"I often procrastinate because of my perfectionism.",
"I am generally more casual than formal.",
"I have a lot of trouble relaxing and slowing down.",
"I am able to freely share my interests and feelings with others."];

var medical_questions = ["I am passionate about working with the human body.",
"I have great communication and social skills.",
"I really enjoy supporting others in any way.",
"I enjoy synthesizing complex information to arrive at an answer.",
"I am adaptable and deal with stress well.",
"I am willing to work hard and smart to become better.",
"I am considered as an excellent teamplayer.",
"I am excellent at dealing with fine details.",
"I only choose a medical career because it will make me rich.",
"I don't really like working with people.",
"I have a hard time focusing and working for long hours.",
"I often feel overwhelmed by change and chaos.",
"I often lie and cheat to get ahead."];